In [ ]:
a=[10,40,506,76]
print(a)

[10, 40, 506, 76]


In [ ]:
import math

In [ ]:
math.sqrt(7)

2.6457513110645907

In [ ]:
#import the package
import numpy as np

In [ ]:
# array: in numpy library the array function will tak the list and make them into dimensions


b = np.array([10,20,30,50])
print(b)

[10 20 30 50]


In [ ]:
print(b.shape) # how many points are there

(4,)


In [ ]:
print(b.ndim) # show number of dims

1


In [ ]:
a = [10,20,100,300]
print(a)

print(a.shape)
print(a.ndim)

[10, 20, 100, 300]


AttributeError: ignored

In [ ]:
a = np.array([10,20,100,300])
print(a)

print(a.shape)
print(a.ndim)

[ 10  20 100 300]
(4,)
1


In [ ]:
a = np.array([[1,2,3] , [10,11,12] , [21,22,23]])
print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[[ 1  2  3]
 [10 11 12]
 [21 22 23]]
<class 'numpy.ndarray'>
(3, 3)
2


In [ ]:
print(a[2][1])

22


- `arange -> same like range only but it will work like a dimension`

- `reshape -> reshape the data how you want `

In [ ]:
for i in range(1,11):
  print(i,end=' ')

1 2 3 4 5 6 7 8 9 10 

In [ ]:
b=np.arange(1,11)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
1


In [ ]:
a=np.arange(1,61)
print(a)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
(10,)
1


In [ ]:
a=np.arange(1,61).reshape(12,5)
print(a)
print(a.shape)
print(a.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]
(12, 5)
2


In [ ]:
print(a[12][1]) #because index is staring with zero, so we can call with n-1

IndexError: ignored

In [ ]:
print(a[11][1])

57


In [ ]:
a=np.arange(1,61).reshape(5,6,2)
print(a)
print(a.shape)
print(a.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]
  [19 20]
  [21 22]
  [23 24]]

 [[25 26]
  [27 28]
  [29 30]
  [31 32]
  [33 34]
  [35 36]]

 [[37 38]
  [39 40]
  [41 42]
  [43 44]
  [45 46]
  [47 48]]

 [[49 50]
  [51 52]
  [53 54]
  [55 56]
  [57 58]
  [59 60]]]
(5, 6, 2)
3


In [ ]:
print(a[4][3][0])

55


In [ ]:
a = np.array([[1,2,3] , [10,11,12] , [21,22,23]])
print(a)
print(a.shape)  # how many rows and how many columns
print(a.ndim) # total how many dims
print(a.size) # total how many values are there

[[ 1  2  3]
 [10 11 12]
 [21 22 23]]
(3, 3)
2
9


In [ ]:
# zeros -> we can create zero
# defaultly -> numpy is an float64 bit type


a = np.zeros((5,6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# zeros -> we can create zero
# defaultly -> numpy is an float64 bit type


a = np.zeros((5,6) ,dtype = np.int8)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
# ones -> will create ones
a = np.ones((5,6))
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.ones((5,5), dtype=np.int64)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
a=np.twos((3,3), dtype=np.int64)
print(a)

AttributeError: ignored

In [ ]:
# full -> we can fill our own value
#doubt
a = np.full((5,6) , 9 , dtype = np.float64)
print(a)

[[9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9.]]


In [ ]:
# eye -> identity matrix

a = np.eye(2,2 , dtype = np.int64)
a

array([[1, 0],
       [0, 1]])

In [ ]:
a=np.eye(3,3, dtype=np.int64)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
a = np.arange(1,11)
print(a)
print(a.ndim)
print(a[4]) # USE index for value calling in 1D

[ 1  2  3  4  5  6  7  8  9 10]
1
5


In [ ]:
print(a.min())

1


In [ ]:
print(a.max())

10


In [ ]:
a.sort()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**in Numpy**

- `axis = 1 -> rows `
- `axis = 0 -> columns`

In [ ]:
a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])
print(a)

[[ 11  24  13]
 [101  11 122]
 [121  20   2]]


In [ ]:
a.argmax(axis = 1)

array([1, 2, 0])

In [ ]:
a.argmin(axis=0)

array([0, 1, 2])

In [ ]:
# ravel = convert any dimes to 1d
# transpose = rows to columns and columns to rows
# concatinate = add 2 numpy arrays:


In [ ]:
a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])
print(a)

[[ 11  24  13]
 [101  11 122]
 [121  20   2]]


In [ ]:
a.ravel()

array([ 11,  24,  13, 101,  11, 122, 121,  20,   2])

In [ ]:
a = np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
# transpose:

a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])
print(a)

[[ 11  24  13]
 [101  11 122]
 [121  20   2]]


In [ ]:
a.T

array([[ 11, 101, 121],
       [ 24,  11,  20],
       [ 13, 122,   2]])

In [ ]:
# concatinate

a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])

b = np.array([[1,2,3],[10,11,12],[99,98,200]])

c = np.concatenate((a,b))

print(c)

[[ 11  24  13]
 [101  11 122]
 [121  20   2]
 [  1   2   3]
 [ 10  11  12]
 [ 99  98 200]]


In [ ]:
a = np.random.randint(21,49 , 3) # in between the range randomlly a values will be picked
a #21 TO 49 ANY 3 RANDOM NUMBERS PICKED.

array([48, 23, 29])

In [ ]:
a = np.random.randn(5,6)
a

array([[-0.2115828 , -0.93175195, -1.24314209,  2.03309458,  1.60895521,
         0.91078742],
       [ 0.06320105,  0.64466447,  0.93747748,  1.30423646, -0.7626736 ,
        -1.56821478],
       [ 2.29179187,  0.47337769,  0.98514165, -0.28717527,  0.23998334,
         1.60850112],
       [-0.35700781, -0.01511977, -0.17475733, -0.30115933,  0.30972804,
        -0.02643893],
       [ 0.10508047, -1.84610017, -0.28175179, -0.93153279,  1.35851421,
         2.50072004]])

In [ ]:
a = np.random.random((5,5)) # random values in between 0 to 1
a

array([[0.52605508, 0.65577162, 0.67476502, 0.01896569, 0.51262403],
       [0.67888586, 0.54485594, 0.76831841, 0.48742382, 0.31194979],
       [0.89893776, 0.69277775, 0.23873448, 0.39409679, 0.64387076],
       [0.34143452, 0.68542537, 0.39501331, 0.08726052, 0.09324324],
       [0.14464751, 0.56274911, 0.19824733, 0.76818782, 0.7766978 ]])

In [ ]:
# math operations

a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])

a

array([[ 11,  24,  13],
       [101,  11, 122],
       [121,  20,   2]])

In [ ]:
a+15

array([[ 26,  39,  28],
       [116,  26, 137],
       [136,  35,  17]])

In [ ]:
np.add(a,10)

array([[ 21,  34,  23],
       [111,  21, 132],
       [131,  30,  12]])

In [ ]:
a = np.array([[11,24,13] , [101,11,122] , [121,20,2]])

b = np.array([[1,2,3],[10,11,12],[99,98,200]])


print(a + b)

[[ 12  26  16]
 [111  22 134]
 [220 118 202]]


In [ ]:
# Create an 1D input array
a = np.array([5,3,7,567,56,43423])
print(f'Original array {a}')

# Reverse numpy array
# Using slicing notation
b = a[::-1]
print(f'Reversed array {b}')

Original array [    5     3     7   567    56 43423]
Reversed array [43423    56   567     7     3     5]


In [ ]:
a=np.array([[2,3,5],[5,6,7],[8,9,0]])
print(f'original array{a}')
b=a[::-1]
print(f'reverse array{b}')

original array[[2 3 5]
 [5 6 7]
 [8 9 0]]
reverse array[[8 9 0]
 [5 6 7]
 [2 3 5]]


In [ ]:
np.flipud(a)

array([43423,    56,   567,     7,     3,     5])