In [ ]:
import numpy as np
import pandas as pd


**2 concept we need to learn in pandas**
-`series->it works in 1d frames.`
-`DataFrame -> multiple Dims -> like structured data`


In [ ]:
a=np.arange(1,21)
print(a)
print(a.ndim)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)


In [ ]:
a=pd.Series(np.arange(1,21))
print(a)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
dtype: int64


In [ ]:
a=pd.Series([23,45,67,89,98],index=['r1','r2','r3','r4','r5'])
print(a)

r1    23
r2    45
r3    67
r4    89
r5    98
dtype: int64


In [ ]:
a['r2']

45

In [ ]:
a['r2':]

r2    45
r3    67
r4    89
r5    98
dtype: int64

**DataFrame in panda**

it is a excel sheet data.

In [ ]:
a=np.arange(1,51).reshape(10,5)
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
2
(10, 5)


In [ ]:
b=pd.DataFrame(np.arange(1,51).reshape(10,5))
print(b)

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30
6  31  32  33  34  35
7  36  37  38  39  40
8  41  42  43  44  45
9  46  47  48  49  50


In [ ]:
b=pd.DataFrame(np.arange(1,51).reshape(10,5), columns=['A','B','C','D','E'], index=['a','b','c','d','e','f','g','h','i','j'])
b

A   B   C   D   E
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20
e  21  22  23  24  25
f  26  27  28  29  30
g  31  32  33  34  35
h  36  37  38  39  40
i  41  42  43  44  45
j  46  47  48  49  50

In [ ]:
a={'Name':['sai','ram','lokesh','mainkanta','csdgth'], 'Age':[21,23,25,26,28],'Location':['hyderabad','vijayawada','chennai','banglore','mumbai']}
a

{'Name': ['sai', 'ram', 'lokesh', 'mainkanta', 'csdgth'],
 'Age': [21, 23, 25, 26, 28],
 'Location': ['hyderabad', 'vijayawada', 'chennai', 'banglore', 'mumbai']}

In [ ]:
c=pd.DataFrame(a)
c

Name  Age    Location
0        sai   21   hyderabad
1        ram   23  vijayawada
2     lokesh   25     chennai
3  mainkanta   26    banglore
4     csdgth   28      mumbai

In [ ]:
c.to_csv('example.csv')

In [ ]:
c

Name  Age    Location
0        sai   21   hyderabad
1        ram   23  vijayawada
2     lokesh   25     chennai
3  mainkanta   26    banglore
4     csdgth   28      mumbai

In [ ]:
c['location'][2] #name should match name not match we get an error.

KeyError: ignored

In [ ]:
c['Location'][2]

'chennai'


difference between loc and iloc function in pandas

loc works diretly with index which is showing and n-1 logic is not applicable and complete opposite to loc is nothing but iloc

In [ ]:
c

Name  Age    Location
0        sai   21   hyderabad
1        ram   23  vijayawada
2     lokesh   25     chennai
3  mainkanta   26    banglore
4     csdgth   28      mumbai

In [ ]:
c.loc[:3, :'Age']

Name  Age
0        sai   21
1        ram   23
2     lokesh   25
3  mainkanta   26

In [ ]:
c.loc[1:3,'Age':'Location']

Age    Location
1   23  vijayawada
2   25     chennai
3   26    banglore

In [ ]:
# iloc -> it works with pure index and n-1

In [ ]:
c

Name  Age    Location
0        sai   21   hyderabad
1        ram   23  vijayawada
2     lokesh   25     chennai
3  mainkanta   26    banglore
4     csdgth   28      mumbai

In [ ]:
c.iloc[0:3,0:2]

Name  Age
0     sai   21
1     ram   23
2  lokesh   25

In [ ]:
c.iloc[:4,:3]

Name  Age    Location
0        sai   21   hyderabad
1        ram   23  vijayawada
2     lokesh   25     chennai
3  mainkanta   26    banglore

In [ ]:
ds=pd.read_csv("/content/Titanic-Dataset.csv")
ds

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# finally we loded the dataset:
# we can do all the operations on this data which is in df -> so that it is not going to effect original one

# info -> get complete information about the dataset.
# shape -> find number of rows and columns.
# size -> used to find total values
# labels -> check in column
# unique -
# value_counts
# head
# tail
# columns
# rename
# fillna
# dropna
# sample
# select_dtype functions
# concat
# isnull().sum()
# drop using axis = 0 and axis = 1

In [ ]:
ds

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# head and tail
# head -> print only first 5 rows
# tail -> last 5 rows

In [ ]:
ds.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
ds.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
# shape -> rows and columns

In [ ]:
ds.shape

(891, 12)

In [ ]:
# size: total values
ds.size

10692

In [ ]:
# finding labels

In [ ]:
ds.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
ds['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
ds['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
ds.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
ds=ds.rename(columns={'Sex':'Gender'})

In [ ]:
ds.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# sample -> randomlly print some rows which mentioned

ds.sample(5)

PassengerId  Survived  Pclass  \
855          856         1       3   
409          410         0       3   
709          710         1       3   
436          437         0       3   
668          669         0       3   

                                                  Name  Gender   Age  SibSp  \
855                         Aks, Mrs. Sam (Leah Rosen)  female  18.0      0   
409                                 Lefebre, Miss. Ida  female   NaN      3   
709  Moubarek, Master. Halim Gonios ("William George")    male   NaN      1   
436               Ford, Miss. Doolina Margaret "Daisy"  female  21.0      2   
668                                    Cook, Mr. Jacob    male  43.0      0   

     Parch      Ticket     Fare Cabin Embarked  
855      1      392091   9.3500   NaN        S  
409      1        4133  25.4667   NaN        S  
709      1        2661  15.2458   NaN        C  
436      2  W./C. 6608  34.3750   NaN        S  
668      0    A/5 3536   8.0500   NaN        S

- `in pandas`

- `axis = 1 -> columns `
- `axis = 0 -> rows `

In [ ]:
ds=ds.drop(['Name'],axis=1)

In [ ]:
ds.tail()

PassengerId  Survived  Pclass  Gender   Age  SibSp  Parch      Ticket  \
886          887         0       2    male  27.0      0      0      211536   
887          888         1       1  female  19.0      0      0      112053   
888          889         0       3  female   NaN      1      2  W./C. 6607   
889          890         1       1    male  26.0      0      0      111369   
890          891         0       3    male  32.0      0      0      370376   

      Fare Cabin Embarked  
886  13.00   NaN        S  
887  30.00   B42        S  
888  23.45   NaN        S  
889  30.00  C148        C  
890   7.75   NaN        Q

In [ ]:
# select_dtype -> you can select columns based on data type

In [ ]:
ds.head()

PassengerId  Survived  Pclass  Gender   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [ ]:
categorical_data = ds.select_dtypes(include = 'object')
categorical_data

Gender            Ticket Cabin Embarked
0      male         A/5 21171   NaN        S
1    female          PC 17599   C85        C
2    female  STON/O2. 3101282   NaN        S
3    female            113803  C123        S
4      male            373450   NaN        S
..      ...               ...   ...      ...
886    male            211536   NaN        S
887  female            112053   B42        S
888  female        W./C. 6607   NaN        S
889    male            111369  C148        C
890    male            370376   NaN        Q

[891 rows x 4 columns]

In [ ]:
# numberical data

numerical_data = ds.select_dtypes(exclude = 'object')
numerical_data

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [ ]:
# check null values -> isnull().sum()
# fill na
# dropna
# rescale

In [ ]:
# find null values

ds.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
ds.isnull()

PassengerId  Survived  Pclass  Gender    Age  SibSp  Parch  Ticket  \
0          False     False   False   False  False  False  False   False   
1          False     False   False   False  False  False  False   False   
2          False     False   False   False  False  False  False   False   
3          False     False   False   False  False  False  False   False   
4          False     False   False   False  False  False  False   False   
..           ...       ...     ...     ...    ...    ...    ...     ...   
886        False     False   False   False  False  False  False   False   
887        False     False   False   False  False  False  False   False   
888        False     False   False   False   True  False  False   False   
889        False     False   False   False  False  False  False   False   
890        False     False   False   False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 11 columns]

In [ ]:
# fillna

ds['Age_filled'] = ds['Age'].fillna(10)


In [ ]:
ds.head(15)

PassengerId  Survived  Pclass  Gender   Age  SibSp  Parch  \
0             1         0       3    male  22.0      1      0   
1             2         1       1  female  38.0      1      0   
2             3         1       3  female  26.0      0      0   
3             4         1       1  female  35.0      1      0   
4             5         0       3    male  35.0      0      0   
5             6         0       3    male   NaN      0      0   
6             7         0       1    male  54.0      0      0   
7             8         0       3    male   2.0      3      1   
8             9         1       3  female  27.0      0      2   
9            10         1       2  female  14.0      1      0   
10           11         1       3  female   4.0      1      1   
11           12         1       1  female  58.0      0      0   
12           13         0       3    male  20.0      0      0   
13           14         0       3    male  39.0      1      5   
14           15         0       3  female  14.0      0      0   

              Ticket     Fare Cabin Embarked  Age_filled  
0          A/5 21171   7.2500   NaN        S        22.0  
1           PC 17599  71.2833   C85        C        38.0  
2   STON/O2. 3101282   7.9250   NaN        S        26.0  
3             113803  53.1000  C123        S        35.0  
4             373450   8.0500   NaN        S        35.0  
5             330877   8.4583   NaN        Q        10.0  
6              17463  51.8625   E46        S        54.0  
7             349909  21.0750   NaN        S         2.0  
8             347742  11.1333   NaN        S        27.0  
9             237736  30.0708   NaN        C        14.0  
10           PP 9549  16.7000    G6        S         4.0  
11            113783  26.5500  C103        S        58.0  
12         A/5. 2151   8.0500   NaN        S        20.0  
13            347082  31.2750   NaN        S        39.0  
14            350406   7.8542   NaN        S        14.0

In [ ]:
# dropna remove all the rows which are having null values

In [ ]:
ds=ds.dropna

AttributeError: ignored

In [ ]:
ds

<bound method DataFrame.dropna of      PassengerId  Survived  Pclass  Gender   Age  SibSp  Parch  \
0              1         0       3    male  22.0      1      0   
1              2         1       1  female  38.0      1      0   
2              3         1       3  female  26.0      0      0   
3              4         1       1  female  35.0      1      0   
4              5         0       3    male  35.0      0      0   
..           ...       ...     ...     ...   ...    ...    ...   
886          887         0       2    male  27.0      0      0   
887          888         1       1  female  19.0      0      0   
888          889         0       3  female   NaN      1      2   
889          890         1       1    male  26.0      0      0   
890          891         0       3    male  32.0      0      0   

               Ticket     Fare Cabin Embarked  Age_filled  
0           A/5 21171   7.2500   NaN        S        22.0  
1            PC 17599  71.2833   C85        C        

In [ ]:
c

Name  Age    Location
0        sai   21   hyderabad
1        ram   23  vijayawada
2     lokesh   25     chennai
3  mainkanta   26    banglore
4     csdgth   28      mumbai

In [ ]:
new=pd.DataFrame({'Domain':['CSE','ECE','MECH','EEE','CIVIL']})
new

Domain
0    CSE
1    ECE
2   MECH
3    EEE
4  CIVIL

In [ ]:
x=pd.concat([c,new], axis=1)
x

Name  Age    Location Domain
0        sai   21   hyderabad    CSE
1        ram   23  vijayawada    ECE
2     lokesh   25     chennai   MECH
3  mainkanta   26    banglore    EEE
4     csdgth   28      mumbai  CIVIL